### PR TITLE
Draft: Initial support for loading VtMB .mdl and .vtf files

### PR DESCRIPTION
**Pull request by lfxgroove**
Hey, I've started working on adding support for Vampire the Masquerade Bloodlines files. I started with .mdl files and the corresponding textures used. Wanted to see if I could get some early feedback on if my approach makes sense or if there's some obvious things that need changing before I go any further?

There are a few places with todos etc which I intend to fix before marking this as ready for review. Just wanted to avoid putting lots of time into going the wrong direction.

I've tested loading a baseball bat model which seems to work, the texture also looks okay.

Slightly related issue: #117

### CODE REVIEW

**Comment by REDxEYE** [comment]
Have you seen https://github.com/REDxEYE/SourceIO/tree/vtmb branch? I've implemented a lot of stuff there:
Maps, model, textures and materials

**Comment by REDxEYE** [comment]
Compare your code to my branch and if you can, transplant your changes onto vtmb branch

**Comment by lfxgroove** [comment]
Oh wops, did not see that, I'll take a look and update this PR to target that branch if there's anything of interest left!

**Comment by lfxgroove** [comment]
Looks like you've done waaaay more work than I have in this PR :) Let me know if there's anything I can help with on the branch, closing this!

**Comment by REDxEYE** [comment]
You can really help by testing VtMB parts of code. Import various models/maps

**Pull request closed without merging**
